In [86]:
import pandas as pd
df=pd.read_csv('orders.csv')

In [11]:
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Noida,46,702.33750,19.182,11.97,12.0,Dairy,Wallet,2.1,1,3.2
1,1000002,Flipkart Minutes,Amritsar,56,1007.30000,19.644,12.74,10.0,Snacks,Cash on Delivery,2.3,0,3.2
2,1000003,Flipkart Minutes,Mumbai,18,1211.66000,16.910,4.85,NaN,Personal Care,Cash on Delivery,3.3,0,3.8
3,1000004,Swiggy Instamart,Delhi,23,1179.05925,5.864,6.44,2.0,Dairy,Credit Card,5.0,1,5.0
4,1000005,Dunzo,Mumbai,44,586.02550,12.470,2.45,13.0,Household,Wallet,3.7,0,4.8

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Order_ID                 1000000 non-null  int64
 1   Company                  1000000 non-null  object
 2   City                     948000 non-null   object
 3   Customer_Age             1000000 non-null  int64
 4   Order_Value              1000000 non-null  float64
 5   Delivery_Time_Min        1000000 non-null  float64
 6   Distance_Km              1000000 non-null  float64
 7   Items_Count              965000 non-null   float64
 8   Product_Category         1000000 non-null  object
 9   Payment_Method           1000000 non-null  object
 10  Customer_Rating          953000 non-null   float64
 11  Discount_Applied         1000000 non-null  int64
 12  Delivery_Partner_Rating  895863 non-null   float64
dtypes: float64(6), int64(3), object(4)
memory usage: 99.2+ MB

In [4]:
df.describe()

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
count,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,965000.000000,953000.000000,1000000.000000,895863.000000
mean,1.500000e+06,38.470387,571.643584,16.452412,7.750231,9.998317,3.042072,0.400883,3.749257
std,2.886753e+05,12.118520,382.784520,6.257172,4.186665,5.478725,1.186872,0.490078,0.722121
min,1.000001e+06,18.000000,50.000000,5.000000,0.500000,1.000000,1.000000,0.000000,2.500000
25%,1.250001e+06,28.000000,287.840150,12.368000,4.130000,5.000000,2.000000,0.000000,3.100000
50%,1.500000e+06,38.000000,531.324600,16.342000,7.740000,10.000000,3.000000,0.000000,3.700000
75%,1.750000e+06,49.000000,796.182500,20.196000,11.380000,15.000000,4.000000,1.000000,4.400000
max,2.000000e+06,59.000000,13877.325000,40.000000,15.000000,19.000000,5.000000,1.000000,5.000000

In [14]:
df.shape

(1000000, 13)

In [6]:
#handling missing values

In [5]:
df.isnull().sum()

Order_ID                        0
Company                         0
City                        52000
Customer_Age                    0
Order_Value                     0
Delivery_Time_Min               0
Distance_Km                     0
Items_Count                 35000
Product_Category                0
Payment_Method                  0
Customer_Rating             47000
Discount_Applied                0
Delivery_Partner_Rating    104137
dtype: int64

In [89]:
df['City']=df['City'].fillna('Unknown')

In [90]:
df['Items_Count'] = df.groupby('Product_Category')['Items_Count'].transform(lambda x: x.fillna(x.median()))

In [91]:
df['rating_missing'] = df['Customer_Rating'].isnull().astype(int)

In [92]:
df['partner_rating_missing'] = df['Delivery_Partner_Rating'].isnull().astype(int)

In [93]:
df.isnull().sum()

Order_ID                        0
Company                         0
City                            0
Customer_Age                    0
Order_Value                     0
Delivery_Time_Min               0
Distance_Km                     0
Items_Count                     0
Product_Category                0
Payment_Method                  0
Customer_Rating             47000
Discount_Applied                0
Delivery_Partner_Rating    104137
rating_missing                  0
partner_rating_missing          0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df.dtypes

Order_ID                     int64
Company                     object
City                        object
Customer_Age                 int64
Order_Value                float64
Delivery_Time_Min          float64
Distance_Km                float64
Items_Count                float64
Product_Category            object
Payment_Method              object
Customer_Rating            float64
Discount_Applied             int64
Delivery_Partner_Rating    float64
rating_missing               int64
partner_rating_missing       int64
dtype: object

In [55]:
#feature engineering

In [94]:
df['age_group'] = pd.qcut(
    df['Customer_Age'], 
    q=3, 
    labels=['young_adult', 'middle-aged', 'senior'],
    duplicates='drop'
)

In [95]:
df['is_late'] = (df['Delivery_Time_Min'] > 30).astype(int)

In [106]:
df['Customer_Rating'] = df['Customer_Rating'].round(1)
df['Delivery_Partner_Rating'] = df['Delivery_Partner_Rating'].round(1)

In [107]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Prafulsql4266@localhost/quick_commerce")

df.to_sql('quick_commerce', con=engine, if_exists='replace', index=False)

1000000